name: Build

on:
  push:
    branches:
      - main
      - build

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    strategy:
      matrix:
        cmd:
          - agent
          - monitor
    uses: clambin/workflows/.github/workflows/build.yaml@docker
    with:
      image: ghcr.io/clambin/uptime-${{ matrix.cmd }}
      dockerfile: build/Dockerfile-${{ matrix.cmd }}
